Enable GRPC Connection pooling
speakeasy-api/speakeasy-go-sdk pull request #23
Opened 2022-10-03 13:18 UTC by ThomasRooney

The GRPC Client has a [resilient connection pool as part of the protocol](https://github.com/grpc/grpc/blob/master/doc/load-balancing.md). In the event of a server-failure, an implicit backoff is created, but the [documentation implies the ClientConnection is kept alive](https://github.com/grpc/grpc/blob/master/doc/connection-backoff.md).

This change causes the GRPC Client to not be re-created between RPC calls. This adhere's to GRPC [best-practices documentation I can find online](https://grpc.io/docs/what-is-grpc/core-concepts/), and [example documentation](https://github.com/grpc/grpc-go/blob/master/examples/route_guide/client/client.go#L171)

2022-10-03 13:28 UTC, TristanSpeakEasy requested changes
Yep this looks good, it was one of the things I discussed with Anuraag earlier

I think we should look to make the suggested changes in the TODO and we will need a close method

2022-10-03 13:28 UTC, TristanSpeakEasy commented on transport.go
> -	defer conn.Close()
we will need to expose a Close() method (and the appropriate documentation) on the SDK to allow the connection to be closed for clean shutdowns of integrators servers

2022-10-03 13:28 UTC, TristanSpeakEasy commented on transport.go
> +	// TODO: when the interface of the speakeasy middleware instantiation is changed to enable an error to be propagated
shall we just do this change now to simplify the implementation?

2022-10-03 13:28 UTC, TristanSpeakEasy commented on transport.go
> +		conn, err := createConn(context.Background(), c.secure, c.serverURL, c.grpcDialer)
as you are creating a new context here, the one passed in as a parameter to this method can be removed?

2022-10-04 19:30 UTC, simplesagar approved these changes

2022-10-06 14:34 UTC, ThomasRooney commented on capture.go
> +	// This will cause the endpoint latency to be added to the GRPC request/response latency
Doing this makes it a little easier to observe bottlenecks during a load-test. TL;DR "Prettier graphs"

The thinking is:
1. When applying load to a system, generally the response time of that system decreases as it hits various resource limits.
2. If we apply a load test via an external service inline during that service's handling of a HTTP call, we can observe our system scaling successfully if the response time of the external service remains constant and below our ingestion timeout. We can validate this by checking the number of sent requests matching exactly the addition to the number of ingested requests. 
3. As such a load testing tool can incrementally increase the rate of requests at an interval (e.g. double the request rate every 10 seconds), and then we can look at output graphs of response latency over time to work out at which point there is a buckling due to a bottleneck.
4. Lacking inline send, the only way we can correlate maximum load is setting the rate of requests manually, then validating the number of ingested requests against the number of made requests, or reading logs. This works too, but lacks as pretty a graph.

We could alternatively do this by load testing the GRPC Ingress endpoint directly, but tooling for that seems more limited than HTTP based approaches.

2022-10-06 14:47 UTC, TristanSpeakEasy approved these changes

2022-10-10 17:29 UTC, merged